fix: Not sure why only the flake checks are failing in ci atm
Seeing if its this path:. or not got this:
error: Cannot build '/nix/store/c5x1g6w8b48qb4rym36nifmsjmjagd90-treefmt-check.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/jmvjgall5azr01kkpily85r1sjiz78s6-treefmt-check
       Last 4 log lines:
       > On branch main
       > Your branch is up to date with 'origin/main'.
       >
       > nothing to commit, working tree clean
       For full logs, run:
         nix log /nix/store/c5x1g6w8b48qb4rym36nifmsjmjagd90-treefmt-check.drv

My presumption/assumption is this is related to the way path:. changes the
derivation $src. I'm not using lfs so it should be ok to let nix build the ye
olde way before I tried getting lfs to work.